#!/bin/bash

export PKG_CONFIG_DIR=
export PKG_CONFIG_PATH=
export PKG_CONFIG_SYSROOT_DIR=

export PKG_CONFIG_LIBDIR=/usr/x86_64-w64-mingw32/lib/pkgconfig

[[ "$1" == '--version' ]] && exec pkg-config --version
exec pkg-config --define-prefix --static "$@"
